version: "3.7"

services:
  headquarter:
    ports:
      - 6543:6543
      - 8080:8080
    build:
      context: ./
      dockerfile: ./VS-Truong-HQ/Dockerfile
      args:
        - NAME=hq
        - TPORT=9090
    container_name: hq

  externalclient:
    build:
      context: ./
      dockerfile: ./VS-Truong-ExternalClient/Dockerfile
      args:
        - NAME=xclient
    container_name: xclient
    depends_on:
        - headquarter

  producer1:
    build:
      context: ./
      dockerfile: ./VS-Truong-Client/dockerfiles/producer/Dockerfile
      args:
        - ID=1
        - NAME=solar
        - TPORT=9091
    container_name: producer1
    depends_on:
      - headquarter

  producer2:
    build:
      context: ./
      dockerfile: ./VS-Truong-Client/dockerfiles/producer/Dockerfile
      args:
        - ID=2
        - NAME=water
        - TPORT=9092
    container_name: producer2
    depends_on:
      - headquarter

  producer3:
    build:
      context: ./
      dockerfile: ./VS-Truong-Client/dockerfiles/producer/Dockerfile
      args:
        - ID=3
        - NAME=wind
        - TPORT=9093
    container_name: producer3
    depends_on:
      - headquarter

  consumer1:
    build:
      context: ./
      dockerfile: ./VS-Truong-Client/dockerfiles/consumer/Dockerfile
      args:
        - ID=4
        - NAME=consumer1
        - TPORT=9094
    container_name: consumer1
    depends_on:
      - headquarter


